// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7Y2L44Bq-PD5vgdoxYRmaoOTt1utPIE',
    appId: '1:347746325058:web:a9ee6a27b97a85fe8393db',
    messagingSenderId: '347746325058',
    projectId: 'tictactoe-cd2ea',
    authDomain: 'tictactoe-cd2ea.firebaseapp.com',
    storageBucket: 'tictactoe-cd2ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFuhXO3mHn6lO5z7Xq-NdVNtQAulmrkkk',
    appId: '1:347746325058:android:aa7b49e970c4e8248393db',
    messagingSenderId: '347746325058',
    projectId: 'tictactoe-cd2ea',
    storageBucket: 'tictactoe-cd2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPcwSHVZ1shvg-7YZW7T2t8_kmXtOMfY',
    appId: '1:347746325058:ios:acdb9e4b93854d9c8393db',
    messagingSenderId: '347746325058',
    projectId: 'tictactoe-cd2ea',
    storageBucket: 'tictactoe-cd2ea.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPcwSHVZ1shvg-7YZW7T2t8_kmXtOMfY',
    appId: '1:347746325058:ios:acdb9e4b93854d9c8393db',
    messagingSenderId: '347746325058',
    projectId: 'tictactoe-cd2ea',
    storageBucket: 'tictactoe-cd2ea.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu7Y2L44Bq-PD5vgdoxYRmaoOTt1utPIE',
    appId: '1:347746325058:web:0bf1f028e1fb46a68393db',
    messagingSenderId: '347746325058',
    projectId: 'tictactoe-cd2ea',
    authDomain: 'tictactoe-cd2ea.firebaseapp.com',
    storageBucket: 'tictactoe-cd2ea.appspot.com',
  );
}
